<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>WpfEditor.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\rachel-denton-merchantface.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\rachel-denton-merchantface.jpg" />
  </ItemGroup>

</Project>
